[package]
name = "liquidity_math"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.0.1"
orion = { git = "https://github.com/gizatechxyz/orion.git", branch = "main" }
